"use client";

import { useState, useCallback, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import {
  Plane,
  Film,
  BookOpen,
  MoreHorizontal,
  FolderOpen,
  ChevronRight,
  Trash2,
  X,
  CheckCircle2,
  Circle,
  Search,
  Paperclip,
  Eye,
  Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface DiscoverPanelProps {
  onOpenEntry: (id: string) => void;
}

/* ── Category config ──────────────────────────────── */

const CATEGORY_META: Record<
  string,
  {
    icon: React.ElementType;
    gradient: string;
    accent: string;
    bg: string;
    ring: string;
  }
> = {
  Trips: {
    icon: Plane,
    gradient: "from-emerald-500/15 to-teal-600/5",
    accent: "text-emerald-400",
    bg: "bg-emerald-500/10",
    ring: "ring-emerald-500/20",
  },
  Entertainment: {
    icon: Film,
    gradient: "from-violet-500/15 to-purple-600/5",
    accent: "text-violet-400",
    bg: "bg-violet-500/10",
    ring: "ring-violet-500/20",
  },
  "To Read": {
    icon: BookOpen,
    gradient: "from-blue-500/15 to-sky-600/5",
    accent: "text-blue-400",
    bg: "bg-blue-500/10",
    ring: "ring-blue-500/20",
  },
  Other: {
    icon: MoreHorizontal,
    gradient: "from-gray-500/15 to-slate-600/5",
    accent: "text-gray-400",
    bg: "bg-gray-500/10",
    ring: "ring-gray-500/20",
  },
};

function getCategoryMeta(name: string) {
  return (
    CATEGORY_META[name] ?? {
      icon: MoreHorizontal,
      gradient: "from-gray-500/15 to-slate-600/5",
      accent: "text-gray-400",
      bg: "bg-gray-500/10",
      ring: "ring-gray-500/20",
    }
  );
}

/** Format date as DD/MM */
function shortDate(d: Date | string): string {
  const date = new Date(d);
  return `${String(date.getDate()).padStart(2, "0")}/${String(date.getMonth() + 1).padStart(2, "0")}`;
}

/* ── Entry Card (AI-enhanced) ─────────────────────── */

function EntryCard({
  entry,
  selecting,
  isSelected,
  onPointerDown,
  onPointerUp,
  onPointerLeave,
}: {
  entry: any;
  selecting: boolean;
  isSelected: boolean;
  onPointerDown: () => void;
  onPointerUp: () => void;
  onPointerLeave: () => void;
}) {
  const [showOriginal, setShowOriginal] = useState(false);

  const hasSummary = !!entry.summary;
  // The AI title is the entry.title (generated by AI), the raw note is entry.content
  const displayTitle = entry.title || entry.content?.slice(0, 60) || "Untitled";
  const displaySummary = entry.summary;
  const originalNote = entry.content;

  return (
    <div
      onPointerDown={onPointerDown}
      onPointerUp={onPointerUp}
      onPointerLeave={onPointerLeave}
      onContextMenu={(e) => e.preventDefault()}
      className={cn(
        "w-full text-left px-3 py-2.5 transition-colors select-none cursor-pointer",
        selecting && isSelected
          ? "bg-primary/10"
          : "hover:bg-muted/40 active:bg-muted/60"
      )}
    >
      <div className="flex items-start gap-2.5">
        {selecting && (
          <div className="shrink-0 pt-0.5">
            {isSelected ? (
              <CheckCircle2 className="h-4 w-4 text-primary" />
            ) : (
              <Circle className="h-4 w-4 text-muted-foreground/40" />
            )}
          </div>
        )}

        <span className="text-[11px] text-muted-foreground tabular-nums pt-0.5 shrink-0 w-[34px]">
          {shortDate(entry.createdAt)}
        </span>

        <div className="flex-1 min-w-0">
          {/* AI title row */}
          <div className="flex items-center gap-1.5">
            {hasSummary && (
              <Sparkles className="h-3 w-3 text-primary/50 shrink-0" />
            )}
            <p className="text-sm font-medium leading-tight line-clamp-1 flex-1">
              {displayTitle}
            </p>
            {entry.attachmentCount > 0 && (
              <Paperclip className="h-3 w-3 text-muted-foreground shrink-0" />
            )}
            {/* Show original toggle */}
            {hasSummary && originalNote && originalNote !== displayTitle && (
              <button
                onPointerDown={(e) => {
                  e.stopPropagation();
                  setShowOriginal(true);
                }}
                onPointerUp={(e) => {
                  e.stopPropagation();
                  setShowOriginal(false);
                }}
                onPointerLeave={() => setShowOriginal(false)}
                className="p-0.5 rounded hover:bg-muted/60 shrink-0 touch-none"
                title="Hold to see original note"
              >
                <Eye className={cn(
                  "h-3.5 w-3.5 transition-colors",
                  showOriginal ? "text-primary" : "text-muted-foreground/40"
                )} />
              </button>
            )}
          </div>

          {/* AI summary OR original note */}
          {showOriginal ? (
            <p className="text-xs text-foreground/80 mt-1 leading-relaxed line-clamp-4 bg-muted/40 rounded px-1.5 py-1 -mx-1 border border-border/30">
              {originalNote}
            </p>
          ) : hasSummary ? (
            <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed line-clamp-2">
              {displaySummary}
            </p>
          ) : (
            <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed line-clamp-2">
              {originalNote?.slice(0, 150)}
            </p>
          )}

          {/* Tags */}
          {entry.tags?.length > 0 && (
            <div className="flex gap-1 mt-1.5 flex-wrap">
              {entry.tags.slice(0, 3).map((tag: string) => (
                <span
                  key={tag}
                  className="text-[9px] text-muted-foreground bg-muted/60 rounded px-1 py-0.5"
                >
                  {tag}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ── Collapsible Category Section ──────────────────── */

function CategoryAccordion({
  name,
  entries,
  expanded,
  onToggle,
  onOpenEntry,
  selecting,
  selected,
  onLongPress,
  onToggleSelect,
}: {
  name: string;
  entries: any[];
  expanded: boolean;
  onToggle: () => void;
  onOpenEntry: (id: string) => void;
  selecting: boolean;
  selected: Set<string>;
  onLongPress: (id: string) => void;
  onToggleSelect: (id: string) => void;
}) {
  const meta = getCategoryMeta(name);
  const Icon = meta.icon;
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const longPressTriggered = useRef(false);

  const selectedInCategory = entries.filter((e) => selected.has(e.id)).length;

  const handlePointerDown = useCallback(
    (id: string) => {
      longPressTriggered.current = false;
      longPressTimer.current = setTimeout(() => {
        longPressTriggered.current = true;
        onLongPress(id);
      }, 500);
    },
    [onLongPress]
  );

  const handlePointerUp = useCallback(
    (id: string) => {
      if (longPressTimer.current) {
        clearTimeout(longPressTimer.current);
        longPressTimer.current = null;
      }
      if (longPressTriggered.current) {
        longPressTriggered.current = false;
        return;
      }
      if (selecting) {
        onToggleSelect(id);
      } else {
        onOpenEntry(id);
      }
    },
    [selecting, onToggleSelect, onOpenEntry]
  );

  const handlePointerLeave = useCallback(() => {
    if (longPressTimer.current) {
      clearTimeout(longPressTimer.current);
      longPressTimer.current = null;
    }
  }, []);

  return (
    <div
      className={cn(
        "rounded-2xl border border-border/40 overflow-hidden transition-all",
        expanded && `bg-gradient-to-b ${meta.gradient}`
      )}
    >
      {/* Accordion trigger */}
      <button
        onClick={onToggle}
        className={cn(
          "w-full flex items-center gap-3 px-4 py-3.5 transition-colors",
          !expanded && "hover:bg-muted/40"
        )}
      >
        <div
          className={cn(
            "flex items-center justify-center h-8 w-8 rounded-lg ring-1",
            meta.bg,
            meta.ring,
            meta.accent
          )}
        >
          <Icon className="h-4 w-4" />
        </div>
        <span className="text-sm font-semibold flex-1 text-left">{name}</span>
        {selecting && selectedInCategory > 0 && (
          <Badge variant="default" className="text-[10px] h-5 tabular-nums mr-1">
            {selectedInCategory}
          </Badge>
        )}
        <Badge
          variant="secondary"
          className="text-[10px] h-5 tabular-nums mr-1"
        >
          {entries.length}
        </Badge>
        <ChevronRight
          className={cn(
            "h-4 w-4 text-muted-foreground transition-transform duration-200",
            expanded && "rotate-90"
          )}
        />
      </button>

      {/* Expanded content */}
      {expanded && (
        <div className="px-3 pb-3">
          {entries.length === 0 ? (
            <div className="text-center py-6 text-muted-foreground text-xs">
              No entries yet
            </div>
          ) : (
            <div className="rounded-xl border border-border/30 bg-card/70 backdrop-blur-sm overflow-hidden divide-y divide-border/20">
              {entries.map((entry) => (
                <EntryCard
                  key={entry.id}
                  entry={entry}
                  selecting={selecting}
                  isSelected={selected.has(entry.id)}
                  onPointerDown={() => handlePointerDown(entry.id)}
                  onPointerUp={() => handlePointerUp(entry.id)}
                  onPointerLeave={handlePointerLeave}
                />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/* ── Main Panel ────────────────────────────────────── */

const CATEGORY_ORDER = ["Trips", "Entertainment", "To Read", "Other"];

export function DiscoverPanel({ onOpenEntry }: DiscoverPanelProps) {
  const feed = trpc.discover.feed.useQuery(undefined, { retry: 2 });
  const [expanded, setExpanded] = useState<Set<string>>(new Set(CATEGORY_ORDER));
  const [selecting, setSelecting] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [search, setSearch] = useState("");

  const utils = trpc.useUtils();

  const deleteMany = trpc.entry.deleteMany.useMutation({
    onSuccess: ({ deleted }) => {
      toast.success(`Deleted ${deleted} idea${deleted === 1 ? "" : "s"}`);
      setSelecting(false);
      setSelected(new Set());
      utils.discover.feed.invalidate();
      utils.entry.list.invalidate();
      utils.entry.stats.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const toggleCategory = (cat: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat);
      else next.add(cat);
      return next;
    });
  };

  const exitSelection = useCallback(() => {
    setSelecting(false);
    setSelected(new Set());
  }, []);

  const toggleSelect = useCallback((id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const handleLongPress = useCallback((id: string) => {
    setSelecting(true);
    setSelected(new Set([id]));
  }, []);

  /* Loading skeleton */
  if (feed.isLoading) {
    return (
      <div className="h-full overflow-y-auto pt-12 pb-4 space-y-4">
        <div className="flex items-center gap-2 px-4">
          <FolderOpen className="h-5 w-5 text-primary" />
          <h1 className="text-lg font-semibold">Digital Dashboard</h1>
        </div>
        <div className="px-4 space-y-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-14 w-full rounded-2xl" />
          ))}
        </div>
      </div>
    );
  }

  /* Error state */
  if (feed.isError) {
    return (
      <div className="h-full overflow-y-auto pt-12 pb-4 space-y-4">
        <div className="flex items-center gap-2 px-4">
          <FolderOpen className="h-5 w-5 text-primary" />
          <h1 className="text-lg font-semibold">Digital Dashboard</h1>
        </div>
        <div className="text-center py-16 text-muted-foreground">
          <FolderOpen className="h-12 w-12 mx-auto mb-4 opacity-20" />
          <p className="text-sm">Could not load dashboard</p>
          <button
            onClick={() => feed.refetch()}
            className="text-sm text-primary mt-2 underline"
          >
            Try again
          </button>
        </div>
      </div>
    );
  }

  const data = feed.data;
  let allEntries = data?.entries ?? [];

  // Apply search filter
  if (search) {
    const q = search.toLowerCase();
    allEntries = allEntries.filter(
      (e) =>
        e.title?.toLowerCase().includes(q) ||
        e.summary?.toLowerCase().includes(q) ||
        e.content?.toLowerCase().includes(q) ||
        e.tags?.some((t: string) => t.toLowerCase().includes(q))
    );
  }

  // Group entries by category name
  const grouped: Record<string, any[]> = {};
  for (const cat of CATEGORY_ORDER) {
    grouped[cat] = [];
  }
  for (const entry of allEntries) {
    const catName = entry.categoryName ?? "Other";
    if (!grouped[catName]) grouped[catName] = [];
    grouped[catName].push(entry);
  }

  // Also collect any dynamic categories not in the fixed list
  const dynamicCategories = Object.keys(grouped).filter(
    (c) => !CATEGORY_ORDER.includes(c)
  );
  const allCategories = [...CATEGORY_ORDER, ...dynamicCategories];

  const hasEntries = (data?.entries ?? []).length > 0;

  const selectAllVisible = () => {
    setSelected(new Set(allEntries.map((e) => e.id)));
  };

  return (
    <div className="flex flex-col h-dvh bg-background">
      {/* Header */}
      <div className="px-4 pt-10 pb-2 shrink-0">
        {selecting ? (
          /* Selection mode header */
          <div className="flex items-center gap-2 mb-2">
            <button
              onClick={exitSelection}
              className="p-1 -ml-1 rounded-lg hover:bg-muted"
            >
              <X className="h-5 w-5" />
            </button>
            <span className="text-sm font-semibold flex-1">
              {selected.size} selected
            </span>
            <button
              onClick={selectAllVisible}
              className="text-xs text-primary font-medium px-2 py-1 rounded-lg hover:bg-primary/10"
            >
              Select all
            </button>
            <button
              onClick={() => {
                if (selected.size === 0) return;
                deleteMany.mutate({ ids: Array.from(selected) });
              }}
              disabled={selected.size === 0 || deleteMany.isPending}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all",
                selected.size > 0
                  ? "bg-destructive text-destructive-foreground hover:bg-destructive/90"
                  : "bg-muted text-muted-foreground"
              )}
            >
              <Trash2 className="h-3.5 w-3.5" />
              Delete{deleteMany.isPending ? "…" : ""}
            </button>
          </div>
        ) : (
          /* Normal header */
          <>
            <div className="flex items-center gap-2 mb-1">
              <FolderOpen className="h-5 w-5 text-primary" />
              <h1 className="text-lg font-semibold">Digital Dashboard</h1>
              <span className="text-xs text-muted-foreground ml-auto tabular-nums">
                {allEntries.length} ideas
              </span>
            </div>
            {hasEntries && (
              <p className="text-[11px] text-muted-foreground/60 px-0.5 mb-2">
                AI-organized across {allCategories.filter((c) => (grouped[c]?.length ?? 0) > 0).length} categories &middot; hold to select
              </p>
            )}

            {/* Search */}
            {hasEntries && (
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <input
                  type="text"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search ideas..."
                  className="w-full rounded-xl border border-border/60 bg-card pl-9 pr-8 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40 focus:border-primary/40 placeholder:text-muted-foreground/60"
                />
                {search && (
                  <button
                    onClick={() => setSearch("")}
                    className="absolute right-2.5 top-1/2 -translate-y-1/2 p-0.5 rounded-full hover:bg-muted"
                  >
                    <X className="h-3.5 w-3.5 text-muted-foreground" />
                  </button>
                )}
              </div>
            )}
          </>
        )}
      </div>

      {/* Scrollable category list */}
      <div className="flex-1 min-h-0 overflow-y-auto px-4 pb-6">
        {!hasEntries ? (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <FolderOpen className="h-10 w-10 text-muted-foreground/20 mb-3" />
            <p className="text-sm text-muted-foreground">
              No ideas yet &mdash; swipe right to catch your first
            </p>
          </div>
        ) : (
          <div className="space-y-2.5 mt-2">
            {allCategories.map((cat) => (
              <CategoryAccordion
                key={cat}
                name={cat}
                entries={grouped[cat] ?? []}
                expanded={expanded.has(cat)}
                onToggle={() => toggleCategory(cat)}
                onOpenEntry={onOpenEntry}
                selecting={selecting}
                selected={selected}
                onLongPress={handleLongPress}
                onToggleSelect={toggleSelect}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
